name: CI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Installing Dependencies
        run: npm install
      - name: Build package
        run: chomp build
      - name: Run tests
        run: chomp test
      - name: Authenticate with Registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm logout
          echo "@jspm:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --yes
