name: CI

on:
  push:
    tags:
      - "*"

jobs:
  test-node:
    name: Node.js Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node: ${{ matrix.node }}
      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Installing Dependencies
        run: npm install
      - name: Build package
        run: chomp build
      - name: Run tests
        run: chomp test

  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node: 16.x
      - name: Authenticate with Registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm logout
          echo "@jspm:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --yes
